version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

executors:
  default-executor:
    docker:
      - image: cimg/ruby:3.3.0
    resource_class: large

  default-executor-postgres:
    docker:
      - image: cimg/ruby:3.3.0
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_USER: backend_test
          POSTGRES_DB: backend_test
          POSTGRES_PASSWORD: backend_test
    resource_class: large

jobs:
  standardrb:
    executor: default-executor
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run StandardRB
          command: bundle exec standardrb

  test-ruby:
    parallelism: 4
    executor: default-executor-postgres

    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: backend_test
      PGPASSWORD: backend_test
      RAILS_ENV: test
      COVERAGE: "1"

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - run: exit 0
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
          destination: test_results

workflows:
  test:
    jobs:
      - test-ruby
  lint:
    jobs:
      - standardrb