# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Ruby orb documentation here: https://circleci.com/developer/orbs/orb/circleci/ruby
  ruby: circleci/ruby@2.1.1

executors:
  default-executor:
    docker:
      - image: cimg/ruby:3.3.0
    resource_class: large

  default-executor-postgres:
    docker:
      - image: cimg/ruby:3.3.0
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_USER: backend_test
          POSTGRES_DB: backend_test
          POSTGRES_PASSWORD: backend_test
    resource_class: large

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  standardrb:
    executor: default-executor
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run StandardRB
          command: bundle exec standardrb

  test-ruby:
    parallelism: 4
    executor: default-executor-postgres

    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: backend_test
      PGPASSWORD: backend_test
      RAILS_ENV: test
      COVERAGE: "1"

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - run: exit 0

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - test-ruby
  lint:
    jobs:
      - standardrb